#!/usr/bin/env bash
# This script install nginx on virtual server
sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx restart
