#!/usr/bin/env bash
# This script install nginx on virtual server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx restart
