#!/usr/bin/env bash
# This script install nginx en virtual server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html
searchString="\tlocation / {"
stringReplace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$searchString@$stringReplace@" /etc/nginx/sites-available/default
sudo service nginx restart
