#!/usr/bin/env bash
# This script install nginx on virtual server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo bash -c 'Hello World!' > /usr/share/nginx/html/index.html

REDIRECT='  location\/redirect_me {\n   return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n}\n'
sudo sed -i "30i$REDIRECT" /etc/nginx/sites-available/default

sudo service nginx restart
