#!/usr/bin/env bash
# This script install nginx en virtual server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo service nginx start

searchString="\tlocation / {"
stringReplace="\terror_page 404 /error404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$searchString@$stringReplace@" /etc/nginx/sites-available/default
sudo service nginx restart
