#!/usr/bin/env bash
! Terminating SSL on HAproxy” means that HAproxy is configured to handle
! encrypted traffic, unencrypt it and pass it on to its destination.

! Create a certificate using certbot and configure HAproxy to accept 
!encrypted traffic for your subdomain www..
