#!/usr/bin/env bash
#if 9 say hi
i=1
while [ $i -lt 10 ]
do
	if [ $i = 4 ]; then echo "bad luck"; ((i++))  
	elif [ $i = 8 ]; then echo "good luck"; ((i++))
  else
	  echo "Holberton School"; ((i++))
  fi
   done
