#!/usr/bin/env bash
# a clock script to print out the minutes and hours in a 12 hour period

h=0
m=0
while [ $h -lt 13 ]; do
	case $m in
	0)
		echo "Hour: $h"
		m=$((m + 1))
		;;
	60)
		m=0
		h=$((h + 1))
		;;
	*)
		echo $m
		m=$((m + 1))
		;;
	esac
done
