#!/usr/bin/env bash
# script  install the ufw firewall and setup a few rules on web-01

# install the firewall in servers
sudo apt-get -y update
sudo apt-get -y install ufw

# reset rules to defaults
sudo ufw default deny incoming
sudo ufw default allow outgoing

# allow the rules traffic
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 3306/tcp
sudo ufw enable
